Description: >
  Tabi Idris / Udacity
  CloudFormation file to allow EC2 instances to manage Udagram S3.
Parameters:
  EnvironmentName:
    Description: "An Environment name to tag resources"
    Type: String

Resources:
  IAMRoleUdagram:
    Type: "AWS::IAM::Role"
    Properties:
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "ec2.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"

  IAMUdagramS3IP:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      Roles:
        - Ref: "IAMRoleUdagram"

Outputs:
  IAMRoleUdagram:
    Description: "Allow EC2 instances to manage Web App S3"
    Value: !Ref IAMUdagramS3IP
    Export:
      Name: !Sub ${EnvironmentName}-IAM-NAME
  IAMRoleUdagramArn:
    Description: Iam Instance Profile Arn
    Value: !GetAtt IAMRoleUdagram.Arn
    Export:
      Name: !Sub ${EnvironmentName}-IAM-ARN
